### PR TITLE
Adding barman ssh config to make sure it doesn't get prompted for a host key

### PR DESCRIPTION
**Pull request by rafecolton**
also adding barman config directory and some minor formatting changes

### CODE REVIEW

**Comment by rafecolton** [comment]
Also adding `wal_retention_policy` to the config

**Comment by jszwedko** [comment]
:+1: thanks for cleaning up the spacing too

**Comment by rafecolton** [comment]
@alexschlessinger mind sanity checking?

**Comment by alexschlessinger** [comment]
:+1: lgtm

**Pull request merged**
